[program:nginx]
command=/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/logs/nginx-stdout.log
stderr_logfile=/logs/nginx-stderr.log
