[program:webui]
command=/usr/bin/python3 /app/webui.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/logs/webui-stdout.log
stderr_logfile=/logs/webui-stderr.log
environment=PYTHONUNBUFFERED="1"
